### ISSUE TITLE
Can't use Swift library for making flutter plugin

### ISSUE THREAD

**Issue by pacifio** [sslcommerz/SSLCommerz-Flutter#2]
`flutter doctor -v` result
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.14.6 18G9216 darwin-x64, locale en-BD)
    • Flutter version 2.0.3 at /Users/adib/Developer/flutter
    • Framework revision 4d7946a68d (3 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/adib/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/adib/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/adib/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

## Writing external plugin

I initiated the project with this following command
`flutter create --org com.example --template=plugin --platforms=android,ios -a kotlin -i kotlin flutter_easy_ssl`

It can't find the SSLCommerzSDK's architecture suitable

<img width="877" alt="can't import" src="https://user-images.githubusercontent.com/32670628/123940846-631eb280-d9bb-11eb-8b85-ff64915efb66.png">

Here is the Podspec
```ruby
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint flutter_easy_ssl.podspec` to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'flutter_easy_ssl'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '10.0'

  s.preserve_paths = 'SSLCommerzSDK.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework SSLCommerzSDK' }
  s.vendored_frameworks = 'SSLCommerzSDK.framework'

  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'armv7 arm64' }
  s.swift_version = '5.0'
  s.public_header_files = 'Classes/**/*.h'
end
```

Here is the development pod file structure

<img width="372" alt="development_fs" src="https://user-images.githubusercontent.com/32670628/123941273-cf99b180-d9bb-11eb-946f-f2da96f017cc.png">

## Using directly with flutter project

I added `SSLCommerzSDK.framework` directly to project frameworks

<img width="253" alt="added_to_frameworks" src="https://user-images.githubusercontent.com/32670628/123941806-564e8e80-d9bc-11eb-9478-0e48c3906c98.png">

Turned on `Embed & Sign`

<img width="570" alt="embed" src="https://user-images.githubusercontent.com/32670628/123941951-7da55b80-d9bc-11eb-8acc-05b34e18e227.png">

But it produced the following error

<img width="1009" alt="failed_to_load_module" src="https://user-images.githubusercontent.com/32670628/123942007-8c8c0e00-d9bc-11eb-86a7-ebb40480e8ea.png">

<img width="244" alt="direct_sdk_intregation" src="https://user-images.githubusercontent.com/32670628/123942064-99106680-d9bc-11eb-9c3c-e0c310b99027.png">

As a paid service a decent support for popular frameworks should be added or included . Or even enough documentation to work with a `WebView` library should be added so `flutter` developers can use this reputed service with ease . This makes the Developer Experience worse 😕

### I will continue to update what I find on this , but I ask official `SSLWireless` developers to look into this !

**Comment by rkbi** [comment]
Thanks for your feedback. As stated in the README, this SDK is only for Android.
![image](https://user-images.githubusercontent.com/49746492/124390946-d99b1780-dd0f-11eb-8fb9-d04e5b4cb312.png)

Updated version with iOS / Swift support is being developed and hopefully will be released soon.

**Comment by pacifio** [comment]
Can you give me an estimation of how quickly this can be launched , if possible

**Comment by rkbi** [comment]
As our SDKs go through multiple testing phases before release, we are unable to commit any dates currently.

**Comment by rkbi** [comment]
> Can you give me an estimation of how quickly this can be launched , if possible

New version with iOS support has been published now at - https://pub.dev/packages/flutter_sslcommerz
